name: license_checker
description: Tool to view and check license of a package's dependencies.
version: 0.0.2
homepage: https://github.com/rufman/license_checker

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  args: ^2.3.0
  barbecue: ^0.4.0
  colorize: ^3.0.0
  package_config: ^2.0.2
  pana: ^0.21.9
  path: ^1.7.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  mockito: ^5.1.0
  test: ^1.20.2

executables:
  lic_ck: license_checker
